### ISSUE TITLE
[新增] 磁共振MRT2腰椎矢状位椎体和椎间盘分割数据　xx

### ISSUE THREAD

**Issue by richarddddd198** [linhandev/dataset#12]
数据集名称*：磁共振MRT2腰椎矢状位椎体和椎间盘分割数据
标注内容*（标注的器官/病灶）：	10个椎骨和9个椎间盘
LICENSE*（关于数据集使用和传播的协议，常用LISENCE请写名字，如果是Custome LICENSE请写网址）：暂不知道
下载方式*（下载网址或介绍下载方式的网页）：比赛官方网址https://www.spinesegmentation-challenge.com/。aistudio:https://aistudio.baidu.com/aistudio/datasetdetail/81211
类型（分类/分割/检测/...）：	分割
模态（CT/MR/CXR/...）：	MRT2WI
数量（扫描总数/图片张数）：	172
标签格式：	NIFIT
文件格式：NIFIT

**Comment by linhandev** [comment]
收到，感谢大佬贡献，晚上添加！

**Comment by linhandev** [comment]
数据集和贡献者已经添加，感谢大佬对项目的贡献！
