### ISSUE TITLE
vessel12

### ISSUE THREAD

**Issue by lixinhui541** [linhandev/dataset#15]
数据集名称*：lung vessel segmentation (vessel12)
标注内容*（标注的器官/病灶）：	lung vessel
LICENSE*（关于数据集使用和传播的协议，常用LISENCE请写名字，如果是Custome LICENSE请写网址）：https://tianchi.aliyun.com/dataset/dataDetail?dataId=94812
下载方式*（下载网址或介绍下载方式的)https://tianchi.aliyun.com/dataset/dataDetail?dataId=94812
类型（分类/分割/检测/...）：	分割
模态（CT/MR/CXR/...）：	CT
数量（扫描总数/图片张数）：	
标签格式：	
文件格式：

**Comment by linhandev** [comment]
收到，将于近期添加

**Comment by linhandev** [comment]
已添加，感谢大佬对项目的贡献！
