### ISSUE TITLE
[新增] Duke-Breast-Cancer-MRI

### ISSUE THREAD

**Issue by AlexNmSED** [linhandev/dataset#19]
数据集名称*：Duke-Breast-Cancer-MRI
标注内容*（标注的器官/病灶）：	乳腺癌病变
LICENSE*（关于数据集使用和传播的协议，常用LISENCE请写名字，如果是Custome LICENSE请写网址）：开放协议
下载方式*（下载网址或介绍下载方式的网页）：https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=70226903
类型（分类/分割/检测/...）：	预测
模态（CT/MR/CXR/...）：	MRI
数量（扫描总数/图片张数）：	922
标签格式：	
文件格式：

**Comment by AlexNmSED** [comment]
如果可以，请协助下载。

**Comment by linhandev** [comment]
链接: https://pan.baidu.com/s/1a-MzY0ws_mbTel-N_-VUCA  密码: hdjp
--来自百度网盘超级会员V6的分享
还在上传，不过快了

**Comment by linhandev** [comment]
上传完成了，所有压缩包解压到一个地方就行

**Comment by AlexNmSED** [comment]
感谢你的帮助











XinYu&nbsp;Hao,&nbsp;Master&nbsp;Student
The&nbsp;Alpha&nbsp;Lab&nbsp;(http://thealphalab.org)
School&nbsp;of&nbsp;Software,&nbsp;Dalian&nbsp;University&nbsp;of&nbsp;Technology,&nbsp;Development&nbsp;Zone,&nbsp;Dalian&nbsp;116620,&nbsp;China
***@***.***

---原始邮件---
发件人: "Lin ***@***.***&gt;
发送时间: 2021年11月9日(周二) 晚上10:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [linhandev/dataset] [新增] Duke-Breast-Cancer-MRI (#19)




 
上传完成了，所有压缩包解压到一个地方就行
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dslhash** [comment]
> 链接: https://pan.baidu.com/s/1a-MzY0ws_mbTel-N_-VUCA 密码: hdjp --来自百度网盘超级会员V6的分享 还在上传，不过快了

可以再分享下载一下吗？谢谢您啦
