### ISSUE TITLE
CT Images in COVID-19 数据集有更新

### ISSUE THREAD

**Issue by parap1uie-s** [linhandev/dataset#20]
CT Images in COVID-19有一个part 2的更新，现在AIStuido上只有part 1

https://wiki.cancerimagingarchive.net/display/Public/CT+Images+in+COVID-19#70227107bcab02c187174a288dbcbf95d26179e8

<img width="601" alt="image" src="https://user-images.githubusercontent.com/23453851/140447925-ea7642ac-e235-4817-aeb3-24d58a439ee1.png">

**Comment by linhandev** [comment]
收到，这会就更新
