### ISSUE TITLE
[新增] 添加新数据集　xx

### ISSUE THREAD

**Issue by Amandalala** [linhandev/dataset#21]
TUH EEG信号v1.5.2：
标注内容：癫痫类别	
LICENSE*（关于数据集使用和传播的协议，常用LISENCE请写名字，如果是Custome LICENSE请写网址）：
下载方式*：数据集官网https://isip.piconepress.com/projects/tuh_eeg/html/downloads.shtml
网盘链接: https://pan.baidu.com/s/1bAqp-sEGGPVdYEK5AsJ4ng  密码: nh8r
类型：分类		
数量：总发作数: 2377	
标签格式：癫痫发作类别（FNSZ/GNSZ/SPSZ/CPSZ/ABSZ/TNSZ/CNSZ/TCSZ/ATSZ/MYSZ）	
文件格式：edf

**Comment by linhandev** [comment]
已经添加，感谢大佬贡献！
