### ISSUE TITLE
[新增] 添加新数据集 BCNB Dataset

### ISSUE THREAD

**Issue by super233** [linhandev/dataset#22]
数据集名称*：Early Breast Cancer Core-Needle Biopsy WSI (BCNB) Dataset，早期乳腺癌患者的穿刺活检WSI
标注内容*（标注的器官/病灶）：在早期乳腺癌患者的病理WSI中，标注了部分的肿瘤区域，并提供了一些临床信息（age, tumor size, tumor type, ER, PR, HER2, HER2 expression, histological grading, surgical, Ki67, molecular subtype, number of lymph node metastases, label）
LICENSE*（关于数据集使用和传播的协议，常用LISENCE请写名字，如果是Custome LICENSE请写网址）：https://github.com/bupt-ai-cz/BALNMP#license
下载方式*（下载网址或介绍下载方式的网页）：https://bupt-ai-cz.github.io/BCNB/
类型（分类/分割/检测/...）：	分类
模态（CT/MR/CXR/...）：
数量（扫描总数/图片张数）：1058
标签格式：Excel
文件格式：JPG, Excel

**Comment by linhandev** [comment]
收到，近期将添加。感谢贡献

**Comment by super233** [comment]
好的，感谢

**Comment by linhandev** [comment]
已经添加，大佬可以看一下，有问题可以pr修改
https://github.com/linhandev/dataset#bcnb%E4%B9%B3%E8%85%BA%E7%99%8C%E7%A9%BF%E5%88%BA%E6%B4%BB%E6%A3%80

**Comment by super233** [comment]
好的，感谢
