### ISSUE TITLE
[新增] 添加新数据集　VerSe2019 and VerSe2020

### ISSUE THREAD

**Issue by ChenchenHu007** [linhandev/dataset#5]
请填写数据集基本信息，*为必填项，其他内容请尽量填写．

注：开 Issue 后数据集成功并入项目，您的Github ID不会作为项目合作者在项目主页展示，我们会在项目末尾致谢．如果您希望作为项目合作者被展示请[提交PR](https://github.com/linhandev/dataset/pulls)．

数据集名称*：
标注内容*（标注的器官/病灶）：Spine 
LICENSE*（关于数据集使用和传播的协议，常用LISENCE请写名字，如果是Custome LICENSE请写网址）：CC BY-SA 4.0 License,MIT License.
下载方式*（下载网址或介绍下载方式的网页）：https://github.com/anjany/verse
类型（分类/分割/检测/...）：Segmentation
模态（CT/MR/CXR/...）：CT
数量（扫描总数/图片张数）:
标签格式：json	
文件格式：nii

**Comment by linhandev** [comment]
收到，我们研究一下，尽快更新

**Comment by linhandev** [comment]
已经更新，数据正在上传，已经可以下载了。下次push会给大佬添加项目贡献者。欢迎大佬给项目贡献更多数据集！
