### ISSUE TITLE
冠脉CTA血管分割数据

### ISSUE THREAD

**Issue by lixinhui541** [linhandev/dataset#9]
请填写数据集基本信息，*为必填项，其他内容请尽量填写．

注：开 Issue 后数据集成功并入项目，您的Github ID不会作为项目合作者在项目主页展示，我们会在项目末尾致谢．如果您希望作为项目合作者被展示请[提交PR](https://github.com/linhandev/dataset/pulls)．

数据集名称*：冠脉CTA
标注内容*（标注的器官/病灶）：	冠状动脉
LICENSE*（关于数据集使用和传播的协议，常用LISENCE请写名字，如果是Custome LICENSE请写网址）：https://zenodo.org/record/3819799#.YKccAUQzbIU
下载方式*（下载网址或介绍下载方式的网页）：https://asoca.grand-challenge.org/
类型（分类/分割/检测/...）分割
模态（CT/MR/CXR/...）：	CT
数量（扫描总数/图片张数）：	
标签格式：	
文件格式：

**Comment by linhandev** [comment]
收到，将在近日研究添加。感谢贡献

**Comment by linhandev** [comment]
数据集已添加，License不允许二次分发，如果大佬过了参赛可以把数据格式和标签格式补全一下。已经在文末将大佬加入了贡献者列表。感谢大佬对项目的支持！

**Comment by OtisZZ** [comment]
可以添加这个数据集的下载吗？咨询了作者一直没有回复...实在无法获取数据集的下载了

**Comment by linhandev** [comment]
我这边也没有这个

**Comment by SLEEP-CO** [comment]
请问如何下载这个数据集？

**Comment by jinaozhang** [comment]
已经填完表格提交好久了，还没有通过

**Comment by TousenKaname** [comment]
请问有人拿到 ASOCA 的数据了吗，我想要一下数据，非常急，感谢

**Comment by zfw-cv** [comment]
同问，有人拿到这个数据了么？

**Comment by zx-lhb** [comment]
有人拿到这个数据了吗？同求一份啊

**Comment by liuyx-1** [comment]
I also filled out the form, but I didn't receive any reply. My email address is yuxueliu@bit.edu.cn. Could the friends who downloaded it share it with me, please?
